version: '3.8'

services:
  database:
    image: mysql:8.0.33 
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
    volumes:
      - vidly:/data/database
    
volumes:
  vidly: